---
title: "team"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
defense <- read_excel('cyclonesFootball2020.xlsx', sheet='Defensive')
str(defense)
offense <- read_excel('cyclonesFootball2020.xlsx', sheet='Offensive')
str(offense)
biography <- read_excel('cyclonesFootball2020.xlsx', sheet='Biography')
str(biography)
```

```{r}
defClean <- defense %>% mutate(across(c(Name, Opponent_Opponent),as.factor)) %>% mutate(across(c(Tackles_Solo, Tackles_ASST, Tackles_TFL, Tackles_Sack, Turnover_FF, Turnover_FR, Turnover_INT, Pass_QBH, Pass_PB),as.numeric))
str(defClean)

offClean <- offense %>% mutate(across(c(Name, Opponent_Opponent),as.factor)) %>% mutate(across(c(Receiving_REC, Receiving_YDS, Receiving_TD, Rushing_ATT, Rushing_YDS, Rushing_TD, Passing_YDS, Passing_TD, Passing_INT),as.numeric))
str(offClean)

bioClean <- biography %>% mutate(across(c(Name, Position, Class, Hometown, Highschool),as.factor)) %>%  mutate(across(c(Weight), as.numeric))
str(bioClean)
```

```{r}
offClean %>% pivot_longer(c('Receiving_REC', 'Receiving_YDS'), names_to='stat', values_to = 'score')
```

```{r}
team <- full_join(defClean, offClean, by='Name')
team %>% full_join(biography, by='Name') 
town <- subset(biography, select = c(Name, Hometown))
#ggplot(town, aes(x='Hometown')) + geom_bar()
```
